/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115885-g02430680b0-20240620"
#endif /* AVUTIL_FFVERSION_H */
